import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/share/provider";
import { Toaster } from "sonner";
import LayoutWrapper from "@/components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Yoga With Jen",
  description: "Generated by Yoga With Jen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased `}
      >
        <Providers>
         {/* <LayoutWrapper> */}
         <div>
            <div className="">
              <Toaster richColors position="top-center" />
              <main>{children}</main>
            </div>
          </div>
         {/* </LayoutWrapper> */}
        </Providers>
      </body>
    </html>
  );
}
